DEF FACING_DOWN  EQU $00
DEF FACING_LEFT  EQU $01
DEF FACING_RIGHT EQU $02
DEF FACING_UP    EQU $03


DEF PLAYER_SPRINTING_DOWN_POSE EQU  $04
DEF PLAYER_SPRINTING_LEFT_POSE EQU  $05
DEF PLAYER_SPRINTING_RIGHT_POSE EQU $06
DEF PLAYER_SPRINTING_UP_POSE EQU    $07

DEF PLAYER_ANIM_PICK_UP_ITEM EQU $08

DEF PLAYER_ANIM_EATING EQU $20
DEF PLAYER_ANIM_HOLD_UP_ITEM EQU $21

DEF PLAYER_ANIM_SICKLE EQU $22
DEF PLAYER_ANIM_HOE    EQU $26
DEF PLAYER_ANIM_HAMMER EQU $2A
DEF PLAYER_ANIM_AX     EQU $2E

DEF PLAYER_ANIM_WATERING_SEEDS EQU $3A

DEF PLAYER_ANIM_SPREAD_SEEDS EQU $3E


DEF PLAYER_SPRITE_FACING_DOWN  EQU $47
DEF PLAYER_SPRITE_FACING_LEFT  EQU $48
DEF PLAYER_SPRITE_FACING_RIGHT EQU $49
DEF PLAYER_SPRITE_FACING_UP    EQU $4A

DEF PLAYER_SPRITE_CARRYING_ITEM EQU $4B

DEF PLAYER_ANIM_THROW_ITEM EQU $4F


DEF PLAYER_ANIM_FILL_WATERING_CAN EQU $64

DEF PLAYER_ANIM_STRETCHING1 EQU $99
DEF PLAYER_ANIM_STRETCHING2 EQU $9A

DEF SMALL_ENERGY  EQU 1
DEF MEDIUM_ENERGY EQU 2
DEF LARGE_ENERGY  EQU 3

DEF MAX_ENERGY EQU $64

DEF MAX_ENERGY_INCREASE_VAL EQU 10
