DEF PLAYER_SPRINTING_DOWN_POSE EQU  $04
DEF PLAYER_SPRINTING_LEFT_POSE EQU  $05
DEF PLAYER_SPRINTING_RIGHT_POSE EQU $06
DEF PLAYER_SPRINTING_UP_POSE EQU    $07

DEF PLAYER_HOLDING_ITEM_POSE EQU $21

DEF SMALL_ENERGY  EQU 1
DEF MEDIUM_ENERGY EQU 2
DEF LARGE_ENERGY  EQU 3

DEF MAX_ENERGY EQU $64

DEF MAX_ENERGY_INCREASE_VAL EQU 10
