SECTION "SRAM 0", SRAM

; TODO: Define width and height as constants for defining sram space.
sMapObjectLocation:: ds 6272

sb880::  db 
sb881::  db 
sb882::  db 
; Starts at Day 0. Counts how many days have passed
sCurrentDayCounter::  db 
; Spring = 0, Summer = 1, Fall = 2, Winter = 3
sCurrentSeason::  db 
sb885::  db 
sb886::  db 
sb887::  db 
sb888::  db 
sTimeElapsed::  db 
sb88a::  db 
sb88b::  db 
sb88c::  db 
sb88d::  db 
sb88e::  db 
sb88f::  db 
sb890::  db 
sb891::  db 
sb892::  db 
sb893::  db 
sb894::  db 
sb895::  db 
sb896::  db 
sb897::  db 
sb898::  db 
sb899::  db 
sb89a::  db 
sb89b::  db 
sb89c::  db 
sb89d::  db 
sb89e::  db 
sb89f::  db 
sb8a0::  db 
sb8a1::  db 
sb8a2::  db 
sShedItemFlagList::
sShedSickleFlag::  db 
sShedHoeFlag::  db 
sShedHammerFlag::  db 
sShedAxFlag::  db 
sShedSuperSickleFlag::  db 
sShedSuperHoeFlag::  db 
sShedSuperHammerFlag::  db 
sb8aa::  db 
sShedCowMedicineFlag::  db 
sShedMilkerFlag::  db 
sb8ad::  db 
sShedWateringCanFlag::  db ; 0xb8ae
sb8af::  db 
sb8b0::  db 
sShedPMedicineFlag::  db ; 0xb8b1
sShedMPotionFlag::  db ; 0xb8b2
sb8b3::  db 
sShedGrassSeedsFlag::  db ; 0xb8b4
sShedTurnipSeedsFlag::  db ; 0xb8b5
sShedPotatoSeedsFlag::  db ; 0xb8b6
sb8b7::  db 
sb8b8::  db 
sb8b9::  db 
sb8ba::  db 
sb8bb::  db 
sb8bc::  db 
sb8bd::  db 
sb8be::  db 
sb8bf::  db 
sCowFeedFlag::  db ; 0xb8c0
sChickenFeedFlag::  db  ; 0xb8c1
sb8c2::  db 
sb8c3::  db 
sb8c4::  db 
sNumCroissant::  db 
sNumRiceBall::  db 
sNumMeatDumpling::  db 
sb8c8::  db 
sb8c9::  db 
sNumWildGrapeJuice::  db ; 0xb8ca
sNumGreenTea::  db ; 0xb8cb
sb8cc::  db 
sb8cd::  db 
sb8ce::  db 
sb8cf::  db 
sb8d0::  db 
sb8d1::  db 
sNumTurnipSeeds::  db ; 0xb8d2
sNumPotatoSeeds::  db ; 0xb8d3
sb8d4::  db 
sb8d5::  db 
sb8d6::  db 
sb8d7::  db 
sb8d8::  db 
sb8d9::  db 
sNumGrassSeeds::  db ; 0xb8da
; 0 = Cat, 1 = Dog
sCatOrDog::  db ; 0xb8db
sPetName::  ds 4 ; 0xb8dc
sb8e0::  db 
sb8e1::  db 
sb8e2::  db 
sb8e3::  db 
sb8e4::  db 
sb8e5::  db 
sb8e6::  db 
sb8e7::  db 
sb8e8::  db 
sb8e9::  db 
sb8ea::  db 
sb8eb::  db 
; 0 = Male, 1 = Female
sPlayerGender::  db  ; 0xb8ec
sPlayerEnergy::  db 
sPlayerMaxEnergy::  db 
; little endian
sPlayerMoney:: ds 3
sb8f2::  db 
sb8f3::  db 
sPlayerName::  ds 4 ; 0xb8f4
sInventory::  ds 3 ; 0xb8f8
sItemSlot::  db  ; 0xb8fb
sb8fc::  db 
sb8fd::  db 
sb8fe::  db 
sb8ff::  db 
sb900::  db 
sb901::  db 
sb902::  db 
sb903::  db 
; This determines the number of flowers that are loaded in the house
; Max energy gets increases once a berry is eaten.
sNumPowerBerriesEaten::  db 
sb905::  db 
sb906::  db 
sb907::  db 
sCurrentWaterInWateringCan::  db 
sb909::  db 
sb90a::  db 
sb90b::  db 
sb90c::  db 
sb90d::  db 
sb90e::  db 
sb90f::  db 
sb910::  db 
sb911::  db 
sb912::  db 
sb913::  db 
sb914::  db 
sb915::  db 
sb916::  db 
sb917::  db 
sb918::  db 
sb919::  db 
sb91a::  db 
sb91b::  db 
sb91c::  db 
sb91d::  db 
sb91e::  db 
sb91f::  db 
sb920::  db 
sb921::  db 
sb922::  db 
sb923::  db 
sb924::  db 
sb925::  db 
sb926::  db 
sb927::  db 
sb928::  db 
sb929::  db 
sb92a::  db 
sb92b::  db 
sb92c::  db 
sb92d::  db 
sb92e::  db 
sb92f::  db 
sb930::  db 
sb931::  db 
sb932::  db 
sb933::  db 
sb934::  db 
sb935::  db 
sb936::  db 
sb937::  db 
sb938::  db 
sb939::  db 
sb93a::  db 
sb93b::  db 
sb93c::  db 
sb93d::  db 
sb93e::  db 
sb93f::  db 
sb940::  db 
sb941::  db 
sb942::  db 
sb943::  db 
sb944::  db 
sb945::  db 
sNumCowFeed::  db 
sNumChickenFeed::  db 
sb948::  db 
sb949::  db 
sb94a::  db 
sb94b::  db 
sb94c::  db 
sb94d::  db 
sb94e::  db 
sb94f::  db 
sb950::  db 
sb951::  db 
sb952::  db 
sb953::  db 
sb954::  db 
sb955::  db 
sb956::  db 
sb957::  db 
sb958::  db 
sb959::  db 
sb95a::  db 
sb95b::  db 
sb95c::  db 
sb95d::  db 
sb95e::  db 
sb95f::  db 
sb960::  db 
sb961::  db 
sb962::  db 
sb963::  db 
sb964::  db 
sb965::  db 
sb966::  db 
sb967::  db 
sb968::  db 
sb969::  db 
sb96a::  db 
sb96b::  db 
sb96c::  db 
sb96d::  db 
sb96e::  db 
sb96f::  db 
sb970::  db 
sb971::  db 
sb972::  db 
sb973::  db 
sb974::  db 
sb975::  db 
sb976::  db 
sb977::  db 
sb978::  db 
sb979::  db 
sb97a::  db 
sb97b::  db 
sb97c::  db 
sb97d::  db 
sb97e::  db 
sb97f::  db 
sb980::  db 
sb981::  db 
sb982::  db 
sb983::  db 
sb984::  db 
sb985::  db 
sb986::  db 
sb987::  db 
sb988::  db 
sb989::  db 
sb98a::  db 
sb98b::  db 
sb98c::  db 
sb98d::  db 
sb98e::  db 
sb98f::  db 
sb990::  db 
sb991::  db 
sb992::  db 
sb993::  db 
sb994::  db 
sb995::  db 
sb996::  db 
sb997::  db 
sb998::  db 
sb999::  db 
sb99a::  db 
sb99b::  db 
sb99c::  db 
sb99d::  db 
sb99e::  db 
sb99f::  db 
sb9a0::  db 
sb9a1::  db 
sb9a2::  db 
sb9a3::  db 
sb9a4::  db 
sb9a5::  db 
sb9a6::  db 
sb9a7::  db 
sb9a8::  db 
sb9a9::  db 
sb9aa::  db 
sb9ab::  db 
sb9ac::  db 
sb9ad::  db 
sb9ae::  db 
sb9af::  db 
sb9b0::  db 
sb9b1::  db 
sb9b2::  db 
sb9b3::  db 
sb9b4::  db 
sb9b5::  db 
sb9b6::  db 
sb9b7::  db 
sb9b8::  db 
sb9b9::  db 
sb9ba::  db 
sb9bb::  db 
sb9bc::  db 
sb9bd::  db 
sb9be::  db 
sb9bf::  db 
sb9c0::  db 
sb9c1::  db 
sb9c2::  db 
sb9c3::  db 
sb9c4::  db 
sb9c5::  db 
sb9c6::  db 
sb9c7::  db 
sb9c8::  db 
sb9c9::  db 
sb9ca::  db 
sb9cb::  db 
sb9cc::  db 
sb9cd::  db 
sb9ce::  db 
sb9cf::  db 
sb9d0::  db 
sb9d1::  db 
sb9d2::  db 
sb9d3::  db 
sb9d4::  db 
sb9d5::  db 
sb9d6::  db 
sSpriteTotalHappiness::  db 
sSpriteDailyHappiness::  db 
sSpriteDailyAnger::  db 
sb9da::  db 
sb9db::  db 
sb9dc::  db 
sb9dd::  db 
sb9de::  db 
sb9df::  db 
sb9e0::  db 
sb9e1::  db 
sb9e2::  db 
sb9e3::  db 
sb9e4::  db 
sb9e5::  db 
sb9e6::  db 
sb9e7::  db 
sb9e8::  db 
sb9e9::  db 
sb9ea::  db 
sb9eb::  db 
sb9ec::  db 
sb9ed::  db 
sb9ee::  db 
sb9ef::  db 
sb9f0::  db 
sb9f1::  db 
sb9f2::  db 
sb9f3::  db 
sb9f4::  db 
sb9f5::  db 
sb9f6::  db 
sb9f7::  db 
sb9f8::  db 
sb9f9::  db 
sb9fa::  db 
sb9fb::  db 
sb9fc::  db 
sb9fd::  db 
sb9fe::  db 
sb9ff::  db 
sba00::  db 
sba01::  db 
sba02::  db 
sba03::  db 
sba04::  db 
sba05::  db 
sba06::  db 
sba07::  db 
sba08::  db 
sba09::  db 
sba0a::  db 
sba0b::  db 
sba0c::  db 
sba0d::  db 
sba0e::  db 
sba0f::  db 
sba10::  db 
sba11::  db 
sba12::  db 
sba13::  db 
sba14::  db 
sba15::  db 
sba16::  db 
sba17::  db 
sba18::  db 
sba19::  db 
sba1a::  db 
sba1b::  db 
sba1c::  db 
sba1d::  db 
sba1e::  db 
sba1f::  db 
sba20::  db 
sba21::  db 
sba22::  db 
sba23::  db 
sba24::  db 
sba25::  db 
sba26::  db 
sba27::  db 
sba28::  db 
sba29::  db 
sba2a::  db 
sba2b::  db 
sba2c::  db 
sba2d::  db 
sba2e::  db 
sba2f::  db 
sNumShipments::  db 
sba31::  db 
sba32::  db 
sba33::  db 
sba34::  db 
sba35::  db 
sba36::  db 
sba37::  db 
sba38::  db 
sba39::  db 
sba3a::  db 
sba3b::  db 
sba3c::  db 
sba3d::  db 
sba3e::  db 
sPrayedFlag::  db 
sba40::  db 
sba41::  db 
sba42::  db 
sba43::  db 
sba44::  db 
sba45::  db 
sba46::  db 
sba47::  db 
sba48::  db 
sba49::  db 
sba4a::  db 
sba4b::  db 
;sba4c::  db 
;sba4d::  db 
;sba4e::  db 
;sba4f::  db 
;sba50::  db 
;sba51::  db 
;sba52::  db 
;sba53::  db 
;sba54::  db 
;sba55::  db 
;sba56::  db 
;sba57::  db 
;sba58::  db 
;sba59::  db 
;sba5a::  db 
;sba5b::  db 
;sba5c::  db 
;sba5d::  db 
;sba5e::  db 
;sba5f::  db 
;sba60::  db 
;sba61::  db 
;sba62::  db 
;sba63::  db 
;sba64::  db 
;sba65::  db 
;sba66::  db 
;sba67::  db 
;sba68::  db 
;sba69::  db 
;sba6a::  db 
;sba6b::  db 
;sba6c::  db 
;sba6d::  db 
;sba6e::  db 
;sba6f::  db 
;sba70::  db 
;sba71::  db 
;sba72::  db 
;sba73::  db 
;sba74::  db 
;sba75::  db 
;sba76::  db 
;sba77::  db 
;sba78::  db 
;sba79::  db 
;sba7a::  db 
;sba7b::  db 
;sba7c::  db 
;sba7d::  db 
;sba7e::  db 
;sba7f::  db 
;sba80::  db 
;sba81::  db 
;sba82::  db 
;sba83::  db 
;sba84::  db 
;sba85::  db 
;sba86::  db 
;sba87::  db 
;sba88::  db 
;sba89::  db 
;sba8a::  db 
;sba8b::  db 
;sba8c::  db 
;sba8d::  db 
;sba8e::  db 
;sba8f::  db 
;sba90::  db 
;sba91::  db 
;sba92::  db 
;sba93::  db 
;sba94::  db 
;sba95::  db 
;sba96::  db 
;sba97::  db 
;sba98::  db 
;sba99::  db 
;sba9a::  db 
;sba9b::  db 
;sba9c::  db 
;sba9d::  db 
;sba9e::  db 
;sba9f::  db 
;sbaa0::  db 
;sbaa1::  db 
;sbaa2::  db 
;sbaa3::  db 
;sbaa4::  db 
;sbaa5::  db 
;sbaa6::  db 
;sbaa7::  db 
;sbaa8::  db 
;sbaa9::  db 
;sbaaa::  db 
;sbaab::  db 
;sbaac::  db 
;sbaad::  db 
;sbaae::  db 
;sbaaf::  db 
;sbab0::  db 
;sbab1::  db 
;sbab2::  db 
;sbab3::  db 
;sbab4::  db 
;sbab5::  db 
;sbab6::  db 
;sbab7::  db 
;sbab8::  db 
;sbab9::  db 
;sbaba::  db 
;sbabb::  db 
;sbabc::  db 
;sbabd::  db 
;sbabe::  db 
;sbabf::  db 
;sbac0::  db 
;sbac1::  db 
;sbac2::  db 
;sbac3::  db 
;sbac4::  db 
;sbac5::  db 
;sbac6::  db 
;sbac7::  db 
;sbac8::  db 
;sbac9::  db 
;sbaca::  db 
;sbacb::  db 
;sbacc::  db 
;sbacd::  db 
;sbace::  db 
;sbacf::  db 
;sbad0::  db 
;sbad1::  db 
;sbad2::  db 
;sbad3::  db 
;sbad4::  db 
;sbad5::  db 
;sbad6::  db 
;sbad7::  db 
;sbad8::  db 
;sbad9::  db 
;sbada::  db 
;sbadb::  db 
;sbadc::  db 
;sbadd::  db 
;sbade::  db 
;sbadf::  db 
;sbae0::  db 
;sbae1::  db 
;sbae2::  db 
;sbae3::  db 
;sbae4::  db 
;sbae5::  db 
;sbae6::  db 
;sbae7::  db 
;sbae8::  db 
;sbae9::  db 
;sbaea::  db 
;sbaeb::  db 
;sbaec::  db 
;sbaed::  db 
;sbaee::  db 
;sbaef::  db 
;sbaf0::  db 
;sbaf1::  db 
;sbaf2::  db 
;sbaf3::  db 
;sbaf4::  db 
;sbaf5::  db 
;sbaf6::  db 
;sbaf7::  db 
;sbaf8::  db 
;sbaf9::  db 
;sbafa::  db 
;sbafb::  db 
;sbafc::  db 
;sbafd::  db 
;sbafe::  db 
;sbaff::  db 
;sbb00::  db 
;sbb01::  db 
;sbb02::  db 
;sbb03::  db 
;sbb04::  db 
;sbb05::  db 
;sbb06::  db 
;sbb07::  db 
;sbb08::  db 
;sbb09::  db 
;sbb0a::  db 
;sbb0b::  db 
;sbb0c::  db 
;sbb0d::  db 
;sbb0e::  db 
;sbb0f::  db 
;sbb10::  db 
;sbb11::  db 
;sbb12::  db 
;sbb13::  db 
;sbb14::  db 
;sbb15::  db 
;sbb16::  db 
;sbb17::  db 
;sbb18::  db 
;sbb19::  db 
;sbb1a::  db 
;sbb1b::  db 
;sbb1c::  db 
;sbb1d::  db 
;sbb1e::  db 
;sbb1f::  db 
;sbb20::  db 
;sbb21::  db 
;sbb22::  db 
;sbb23::  db 
;sbb24::  db 
;sbb25::  db 
;sbb26::  db 
;sbb27::  db 
;sbb28::  db 
;sbb29::  db 
;sbb2a::  db 
;sbb2b::  db 
;sbb2c::  db 
;sbb2d::  db 
;sbb2e::  db 
;sbb2f::  db 
;sbb30::  db 
;sbb31::  db 
;sbb32::  db 
;sbb33::  db 
;sbb34::  db 
;sbb35::  db 
;sbb36::  db 
;sbb37::  db 
;sbb38::  db 
;sbb39::  db 
;sbb3a::  db 
;sbb3b::  db 
;sbb3c::  db 
;sbb3d::  db 
;sbb3e::  db 
;sbb3f::  db 
;sbb40::  db 
;sbb41::  db 
;sbb42::  db 
;sbb43::  db 
;sbb44::  db 
;sbb45::  db 
;sbb46::  db 
;sbb47::  db 
;sbb48::  db 
;sbb49::  db 
;sbb4a::  db 
;sbb4b::  db 
;sbb4c::  db 
;sbb4d::  db 
;sbb4e::  db 
;sbb4f::  db 
;sbb50::  db 
;sbb51::  db 
;sbb52::  db 
;sbb53::  db 
;sbb54::  db 
;sbb55::  db 
;sbb56::  db 
;sbb57::  db 
;sbb58::  db 
;sbb59::  db 
;sbb5a::  db 
;sbb5b::  db 
;sbb5c::  db 
;sbb5d::  db 
;sbb5e::  db 
;sbb5f::  db 
;sbb60::  db 
;sbb61::  db 
;sbb62::  db 
;sbb63::  db 
;sbb64::  db 
;sbb65::  db 
;sbb66::  db 
;sbb67::  db 
;sbb68::  db 
;sbb69::  db 
;sbb6a::  db 
;sbb6b::  db 
;sbb6c::  db 
;sbb6d::  db 
;sbb6e::  db 
;sbb6f::  db 
;sbb70::  db 
;sbb71::  db 
;sbb72::  db 
;sbb73::  db 
;sbb74::  db 
;sbb75::  db 
;sbb76::  db 
;sbb77::  db 
;sbb78::  db 
;sbb79::  db 
;sbb7a::  db 
;sbb7b::  db 
;sbb7c::  db 
;sbb7d::  db 
;sbb7e::  db 
;sbb7f::  db 
;sbb80::  db 
;sbb81::  db 
;sbb82::  db 
;sbb83::  db 
;sbb84::  db 
;sbb85::  db 
;sbb86::  db 
;sbb87::  db 
;sbb88::  db 
;sbb89::  db 
;sbb8a::  db 
;sbb8b::  db 
;sbb8c::  db 
;sbb8d::  db 
;sbb8e::  db 
;sbb8f::  db 
;sbb90::  db 
;sbb91::  db 
;sbb92::  db 
;sbb93::  db 
;sbb94::  db 
;sbb95::  db 
;sbb96::  db 
;sbb97::  db 
;sbb98::  db 
;sbb99::  db 
;sbb9a::  db 
;sbb9b::  db 
;sbb9c::  db 
;sbb9d::  db 
;sbb9e::  db 
;sbb9f::  db 
;sbba0::  db 
;sbba1::  db 
;sbba2::  db 
;sbba3::  db 
;sbba4::  db 
;sbba5::  db 
;sbba6::  db 
;sbba7::  db 
;sbba8::  db 
;sbba9::  db 
;sbbaa::  db 
;sbbab::  db 
;sbbac::  db 
;sbbad::  db 
;sbbae::  db 
;sbbaf::  db 
;sbbb0::  db 
;sbbb1::  db 
;sbbb2::  db 
;sbbb3::  db 
;sbbb4::  db 
;sbbb5::  db 
;sbbb6::  db 
;sbbb7::  db 
;sbbb8::  db 
;sbbb9::  db 
;sbbba::  db 
;sbbbb::  db 
;sbbbc::  db 
;sbbbd::  db 
;sbbbe::  db 
;sbbbf::  db 
;sbbc0::  db 
;sbbc1::  db 
;sbbc2::  db 
;sbbc3::  db 
;sbbc4::  db 
;sbbc5::  db 
;sbbc6::  db 
;sbbc7::  db 
;sbbc8::  db 
;sbbc9::  db 
;sbbca::  db 
;sbbcb::  db 
;sbbcc::  db 
;sbbcd::  db 
;sbbce::  db 
;sbbcf::  db 
;sbbd0::  db 
;sbbd1::  db 
;sbbd2::  db 
;sbbd3::  db 
;sbbd4::  db 
;sbbd5::  db 
;sbbd6::  db 
;sbbd7::  db 
;sbbd8::  db 
;sbbd9::  db 
;sbbda::  db 
;sbbdb::  db 
;sbbdc::  db 
;sbbdd::  db 
;sbbde::  db 
;sbbdf::  db 
;sbbe0::  db 
;sbbe1::  db 
;sbbe2::  db 
;sbbe3::  db 
;sbbe4::  db 
;sbbe5::  db 
;sbbe6::  db 
;sbbe7::  db 
;sbbe8::  db 
;sbbe9::  db 
;sbbea::  db 
;sbbeb::  db 
;sbbec::  db 
;sbbed::  db 
;sbbee::  db 
;sbbef::  db 
;sbbf0::  db 
;sbbf1::  db 
;sbbf2::  db 
;sbbf3::  db 
;sbbf4::  db 
;sbbf5::  db 
;sbbf6::  db 
;sbbf7::  db 
;sbbf8::  db 
;sbbf9::  db 
;sbbfa::  db 
;sbbfb::  db 
;sbbfc::  db 
;sbbfd::  db 
;sbbfe::  db 
;sbbff::  db 
;sbc00::  db 
;sbc01::  db 
;sbc02::  db 
;sbc03::  db 
;sbc04::  db 
;sbc05::  db 
;sbc06::  db 
;sbc07::  db 
;sbc08::  db 
;sbc09::  db 
;sbc0a::  db 
;sbc0b::  db 
;sbc0c::  db 
;sbc0d::  db 
;sbc0e::  db 
;sbc0f::  db 
;sbc10::  db 
;sbc11::  db 
;sbc12::  db 
;sbc13::  db 
;sbc14::  db 
;sbc15::  db 
;sbc16::  db 
;sbc17::  db 
;sbc18::  db 
;sbc19::  db 
;sbc1a::  db 
;sbc1b::  db 
;sbc1c::  db 
;sbc1d::  db 
;sbc1e::  db 
;sbc1f::  db 
;sbc20::  db 
;sbc21::  db 
;sbc22::  db 
;sbc23::  db 
;sbc24::  db 
;sbc25::  db 
;sbc26::  db 
;sbc27::  db 
;sbc28::  db 
;sbc29::  db 
;sbc2a::  db 
;sbc2b::  db 
;sbc2c::  db 
;sbc2d::  db 
;sbc2e::  db 
;sbc2f::  db 
;sbc30::  db 
;sbc31::  db 
;sbc32::  db 
;sbc33::  db 
;sbc34::  db 
;sbc35::  db 
;sbc36::  db 
;sbc37::  db 
;sbc38::  db 
;sbc39::  db 
;sbc3a::  db 
;sbc3b::  db 
;sbc3c::  db 
;sbc3d::  db 
;sbc3e::  db 
;sbc3f::  db 
;sbc40::  db 
;sbc41::  db 
;sbc42::  db 
;sbc43::  db 
;sbc44::  db 
;sbc45::  db 
;sbc46::  db 
;sbc47::  db 
;sbc48::  db 
;sbc49::  db 
;sbc4a::  db 
;sbc4b::  db 
;sbc4c::  db 
;sbc4d::  db 
;sbc4e::  db 
;sbc4f::  db 
;sbc50::  db 
;sbc51::  db 
;sbc52::  db 
;sbc53::  db 
;sbc54::  db 
;sbc55::  db 
;sbc56::  db 
;sbc57::  db 
;sbc58::  db 
;sbc59::  db 
;sbc5a::  db 
;sbc5b::  db 
;sbc5c::  db 
;sbc5d::  db 
;sbc5e::  db 
;sbc5f::  db 
;sbc60::  db 
;sbc61::  db 
;sbc62::  db 
;sbc63::  db 
;sbc64::  db 
;sbc65::  db 
;sbc66::  db 
;sbc67::  db 
;sbc68::  db 
;sbc69::  db 
;sbc6a::  db 
;sbc6b::  db 
;sbc6c::  db 
;sbc6d::  db 
;sbc6e::  db 
;sbc6f::  db 
;sbc70::  db 
;sbc71::  db 
;sbc72::  db 
;sbc73::  db 
;sbc74::  db 
;sbc75::  db 
;sbc76::  db 
;sbc77::  db 
;sbc78::  db 
;sbc79::  db 
;sbc7a::  db 
;sbc7b::  db 
;sbc7c::  db 
;sbc7d::  db 
;sbc7e::  db 
;sbc7f::  db 
;sbc80::  db 
;sbc81::  db 
;sbc82::  db 
;sbc83::  db 
;sbc84::  db 
;sbc85::  db 
;sbc86::  db 
;sbc87::  db 
;sbc88::  db 
;sbc89::  db 
;sbc8a::  db 
;sbc8b::  db 
;sbc8c::  db 
;sbc8d::  db 
;sbc8e::  db 
;sbc8f::  db 
;sbc90::  db 
;sbc91::  db 
;sbc92::  db 
;sbc93::  db 
;sbc94::  db 
;sbc95::  db 
;sbc96::  db 
;sbc97::  db 
;sbc98::  db 
;sbc99::  db 
;sbc9a::  db 
;sbc9b::  db 
;sbc9c::  db 
;sbc9d::  db 
;sbc9e::  db 
;sbc9f::  db 
;sbca0::  db 
;sbca1::  db 
;sbca2::  db 
;sbca3::  db 
;sbca4::  db 
;sbca5::  db 
;sbca6::  db 
;sbca7::  db 
;sbca8::  db 
;sbca9::  db 
;sbcaa::  db 
;sbcab::  db 
;sbcac::  db 
;sbcad::  db 
;sbcae::  db 
;sbcaf::  db 
;sbcb0::  db 
;sbcb1::  db 
;sbcb2::  db 
;sbcb3::  db 
;sbcb4::  db 
;sbcb5::  db 
;sbcb6::  db 
;sbcb7::  db 
;sbcb8::  db 
;sbcb9::  db 
;sbcba::  db 
;sbcbb::  db 
;sbcbc::  db 
;sbcbd::  db 
;sbcbe::  db 
;sbcbf::  db 
;sbcc0::  db 
;sbcc1::  db 
;sbcc2::  db 
;sbcc3::  db 
;sbcc4::  db 
;sbcc5::  db 
;sbcc6::  db 
;sbcc7::  db 
;sbcc8::  db 
;sbcc9::  db 
;sbcca::  db 
;sbccb::  db 
;sbccc::  db 
;sbccd::  db 
;sbcce::  db 
;sbccf::  db 
;sbcd0::  db 
;sbcd1::  db 
;sbcd2::  db 
;sbcd3::  db 
;sbcd4::  db 
;sbcd5::  db 
;sbcd6::  db 
;sbcd7::  db 
;sbcd8::  db 
;sbcd9::  db 
;sbcda::  db 
;sbcdb::  db 
;sbcdc::  db 
;sbcdd::  db 
;sbcde::  db 
;sbcdf::  db 
;sbce0::  db 
;sbce1::  db 
;sbce2::  db 
;sbce3::  db 
;sbce4::  db 
;sbce5::  db 
;sbce6::  db 
;sbce7::  db 
;sbce8::  db 
;sbce9::  db 
;sbcea::  db 
;sbceb::  db 
;sbcec::  db 
;sbced::  db 
;sbcee::  db 
;sbcef::  db 
;sbcf0::  db 
;sbcf1::  db 
;sbcf2::  db 
;sbcf3::  db 
;sbcf4::  db 
;sbcf5::  db 
;sbcf6::  db 
;sbcf7::  db 
;sbcf8::  db 
;sbcf9::  db 
;sbcfa::  db 
;sbcfb::  db 
;sbcfc::  db 
;sbcfd::  db 
;sbcfe::  db 
;sbcff::  db 
;sbd00::  db 
;sbd01::  db 
;sbd02::  db 
;sbd03::  db 
;sbd04::  db 
;sbd05::  db 
;sbd06::  db 
;sbd07::  db 
;sbd08::  db 
;sbd09::  db 
;sbd0a::  db 
;sbd0b::  db 
;sbd0c::  db 
;sbd0d::  db 
;sbd0e::  db 
;sbd0f::  db 
;sbd10::  db 
;sbd11::  db 
;sbd12::  db 
;sbd13::  db 
;sbd14::  db 
;sbd15::  db 
;sbd16::  db 
;sbd17::  db 
;sbd18::  db 
;sbd19::  db 
;sbd1a::  db 
;sbd1b::  db 
;sbd1c::  db 
;sbd1d::  db 
;sbd1e::  db 
;sbd1f::  db 
;sbd20::  db 
;sbd21::  db 
;sbd22::  db 
;sbd23::  db 
;sbd24::  db 
;sbd25::  db 
;sbd26::  db 
;sbd27::  db 
;sbd28::  db 
;sbd29::  db 
;sbd2a::  db 
;sbd2b::  db 
;sbd2c::  db 
;sbd2d::  db 
;sbd2e::  db 
;sbd2f::  db 
;sbd30::  db 
;sbd31::  db 
;sbd32::  db 
;sbd33::  db 
;sbd34::  db 
;sbd35::  db 
;sbd36::  db 
;sbd37::  db 
;sbd38::  db 
;sbd39::  db 
;sbd3a::  db 
;sbd3b::  db 
;sbd3c::  db 
;sbd3d::  db 
;sbd3e::  db 
;sbd3f::  db 
;sbd40::  db 
;sbd41::  db 
;sbd42::  db 
;sbd43::  db 
;sbd44::  db 
;sbd45::  db 
;sbd46::  db 
;sbd47::  db 
;sbd48::  db 
;sbd49::  db 
;sbd4a::  db 
;sbd4b::  db 
;sbd4c::  db 
;sbd4d::  db 
;sbd4e::  db 
;sbd4f::  db 
;sbd50::  db 
;sbd51::  db 
;sbd52::  db 
;sbd53::  db 
;sbd54::  db 
;sbd55::  db 
;sbd56::  db 
;sbd57::  db 
;sbd58::  db 
;sbd59::  db 
;sbd5a::  db 
;sbd5b::  db 
;sbd5c::  db 
;sbd5d::  db 
;sbd5e::  db 
;sbd5f::  db 
;sbd60::  db 
;sbd61::  db 
;sbd62::  db 
;sbd63::  db 
;sbd64::  db 
;sbd65::  db 
;sbd66::  db 
;sbd67::  db 
;sbd68::  db 
;sbd69::  db 
;sbd6a::  db 
;sbd6b::  db 
;sbd6c::  db 
;sbd6d::  db 
;sbd6e::  db 
;sbd6f::  db 
;sbd70::  db 
;sbd71::  db 
;sbd72::  db 
;sbd73::  db 
;sbd74::  db 
;sbd75::  db 
;sbd76::  db 
;sbd77::  db 
;sbd78::  db 
;sbd79::  db 
;sbd7a::  db 
;sbd7b::  db 
;sbd7c::  db 
;sbd7d::  db 
;sbd7e::  db 
;sbd7f::  db 
;sbd80::  db 
;sbd81::  db 
;sbd82::  db 
;sbd83::  db 
;sbd84::  db 
;sbd85::  db 
;sbd86::  db 
;sbd87::  db 
;sbd88::  db 
;sbd89::  db 
;sbd8a::  db 
;sbd8b::  db 
;sbd8c::  db 
;sbd8d::  db 
;sbd8e::  db 
;sbd8f::  db 
;sbd90::  db 
;sbd91::  db 
;sbd92::  db 
;sbd93::  db 
;sbd94::  db 
;sbd95::  db 
;sbd96::  db 
;sbd97::  db 
;sbd98::  db 
;sbd99::  db 
;sbd9a::  db 
;sbd9b::  db 
;sbd9c::  db 
;sbd9d::  db 
;sbd9e::  db 
;sbd9f::  db 
;sbda0::  db 
;sbda1::  db 
;sbda2::  db 
;sbda3::  db 
;sbda4::  db 
;sbda5::  db 
;sbda6::  db 
;sbda7::  db 
;sbda8::  db 
;sbda9::  db 
;sbdaa::  db 
;sbdab::  db 
;sbdac::  db 
;sbdad::  db 
;sbdae::  db 
;sbdaf::  db 
;sbdb0::  db 
;sbdb1::  db 
;sbdb2::  db 
;sbdb3::  db 
;sbdb4::  db 
;sbdb5::  db 
;sbdb6::  db 
;sbdb7::  db 
;sbdb8::  db 
;sbdb9::  db 
;sbdba::  db 
;sbdbb::  db 
;sbdbc::  db 
;sbdbd::  db 
;sbdbe::  db 
;sbdbf::  db 
;sbdc0::  db 
;sbdc1::  db 
;sbdc2::  db 
;sbdc3::  db 
;sbdc4::  db 
;sbdc5::  db 
;sbdc6::  db 
;sbdc7::  db 
;sbdc8::  db 
;sbdc9::  db 
;sbdca::  db 
;sbdcb::  db 
;sbdcc::  db 
;sbdcd::  db 
;sbdce::  db 
;sbdcf::  db 
;sbdd0::  db 
;sbdd1::  db 
;sbdd2::  db 
;sbdd3::  db 
;sbdd4::  db 
;sbdd5::  db 
;sbdd6::  db 
;sbdd7::  db 
;sbdd8::  db 
;sbdd9::  db 
;sbdda::  db 
;sbddb::  db 
;sbddc::  db 
;sbddd::  db 
;sbdde::  db 
;sbddf::  db 
;sbde0::  db 
;sbde1::  db 
;sbde2::  db 
;sbde3::  db 
;sbde4::  db 
;sbde5::  db 
;sbde6::  db 
;sbde7::  db 
;sbde8::  db 
;sbde9::  db 
;sbdea::  db 
;sbdeb::  db 
;sbdec::  db 
;sbded::  db 
;sbdee::  db 
;sbdef::  db 
;sbdf0::  db 
;sbdf1::  db 
;sbdf2::  db 
;sbdf3::  db 
;sbdf4::  db 
;sbdf5::  db 
;sbdf6::  db 
;sbdf7::  db 
;sbdf8::  db 
;sbdf9::  db 
;sbdfa::  db 
;sbdfb::  db 
;sbdfc::  db 
;sbdfd::  db 
;sbdfe::  db 
;sbdff::  db 
;sbe00::  db 
;sbe01::  db 
;sbe02::  db 
;sbe03::  db 
;sbe04::  db 
;sbe05::  db 
;sbe06::  db 
;sbe07::  db 
;sbe08::  db 
;sbe09::  db 
;sbe0a::  db 
;sbe0b::  db 
;sbe0c::  db 
;sbe0d::  db 
;sbe0e::  db 
;sbe0f::  db 
;sbe10::  db 
;sbe11::  db 
;sbe12::  db 
;sbe13::  db 
;sbe14::  db 
;sbe15::  db 
;sbe16::  db 
;sbe17::  db 
;sbe18::  db 
;sbe19::  db 
;sbe1a::  db 
;sbe1b::  db 
;sbe1c::  db 
;sbe1d::  db 
;sbe1e::  db 
;sbe1f::  db 
;sbe20::  db 
;sbe21::  db 
;sbe22::  db 
;sbe23::  db 
;sbe24::  db 
;sbe25::  db 
;sbe26::  db 
;sbe27::  db 
;sbe28::  db 
;sbe29::  db 
;sbe2a::  db 
;sbe2b::  db 
;sbe2c::  db 
;sbe2d::  db 
;sbe2e::  db 
;sbe2f::  db 
;sbe30::  db 
;sbe31::  db 
;sbe32::  db 
;sbe33::  db 
;sbe34::  db 
;sbe35::  db 
;sbe36::  db 
;sbe37::  db 
;sbe38::  db 
;sbe39::  db 
;sbe3a::  db 
;sbe3b::  db 
;sbe3c::  db 
;sbe3d::  db 
;sbe3e::  db 
;sbe3f::  db 
;sbe40::  db 
;sbe41::  db 
;sbe42::  db 
;sbe43::  db 
;sbe44::  db 
;sbe45::  db 
;sbe46::  db 
;sbe47::  db 
;sbe48::  db 
;sbe49::  db 
;sbe4a::  db 
;sbe4b::  db 
;sbe4c::  db 
;sbe4d::  db 
;sbe4e::  db 
;sbe4f::  db 
;sbe50::  db 
;sbe51::  db 
;sbe52::  db 
;sbe53::  db 
;sbe54::  db 
;sbe55::  db 
;sbe56::  db 
;sbe57::  db 
;sbe58::  db 
;sbe59::  db 
;sbe5a::  db 
;sbe5b::  db 
;sbe5c::  db 
;sbe5d::  db 
;sbe5e::  db 
;sbe5f::  db 
;sbe60::  db 
;sbe61::  db 
;sbe62::  db 
;sbe63::  db 
;sbe64::  db 
;sbe65::  db 
;sbe66::  db 
;sbe67::  db 
;sbe68::  db 
;sbe69::  db 
;sbe6a::  db 
;sbe6b::  db 
;sbe6c::  db 
;sbe6d::  db 
;sbe6e::  db 
;sbe6f::  db 
;sbe70::  db 
;sbe71::  db 
;sbe72::  db 
;sbe73::  db 
;sbe74::  db 
;sbe75::  db 
;sbe76::  db 
;sbe77::  db 
;sbe78::  db 
;sbe79::  db 
;sbe7a::  db 
;sbe7b::  db 
;sbe7c::  db 
;sbe7d::  db 
;sbe7e::  db 
;sbe7f::  db 
;sbe80::  db 
;sbe81::  db 
;sbe82::  db 
;sbe83::  db 
;sbe84::  db 
;sbe85::  db 
;sbe86::  db 
;sbe87::  db 
;sbe88::  db 
;sbe89::  db 
;sbe8a::  db 
;sbe8b::  db 
;sbe8c::  db 
;sbe8d::  db 
;sbe8e::  db 
;sbe8f::  db 
;sbe90::  db 
;sbe91::  db 
;sbe92::  db 
;sbe93::  db 
;sbe94::  db 
;sbe95::  db 
;sbe96::  db 
;sbe97::  db 
;sbe98::  db 
;sbe99::  db 
;sbe9a::  db 
;sbe9b::  db 
;sbe9c::  db 
;sbe9d::  db 
;sbe9e::  db 
;sbe9f::  db 
;sbea0::  db 
;sbea1::  db 
;sbea2::  db 
;sbea3::  db 
;sbea4::  db 
;sbea5::  db 
;sbea6::  db 
;sbea7::  db 
;sbea8::  db 
;sbea9::  db 
;sbeaa::  db 
;sbeab::  db 
;sbeac::  db 
;sbead::  db 
;sbeae::  db 
;sbeaf::  db 
;sbeb0::  db 
;sbeb1::  db 
;sbeb2::  db 
;sbeb3::  db 
;sbeb4::  db 
;sbeb5::  db 
;sbeb6::  db 
;sbeb7::  db 
;sbeb8::  db 
;sbeb9::  db 
;sbeba::  db 
;sbebb::  db 
;sbebc::  db 
;sbebd::  db 
;sbebe::  db 
;sbebf::  db 
;sbec0::  db 
;sbec1::  db 
;sbec2::  db 
;sbec3::  db 
;sbec4::  db 
;sbec5::  db 
;sbec6::  db 
;sbec7::  db 
;sbec8::  db 
;sbec9::  db 
;sbeca::  db 
;sbecb::  db 
;sbecc::  db 
;sbecd::  db 
;sbece::  db 
;sbecf::  db 
;sbed0::  db 
;sbed1::  db 
;sbed2::  db 
;sbed3::  db 
;sbed4::  db 
;sbed5::  db 
;sbed6::  db 
;sbed7::  db 
;sbed8::  db 
;sbed9::  db 
;sbeda::  db 
;sbedb::  db 
;sbedc::  db 
;sbedd::  db 
;sbede::  db 
;sbedf::  db 
;sbee0::  db 
;sbee1::  db 
;sbee2::  db 
;sbee3::  db 
;sbee4::  db 
;sbee5::  db 
;sbee6::  db 
;sbee7::  db 
;sbee8::  db 
;sbee9::  db 
;sbeea::  db 
;sbeeb::  db 
;sbeec::  db 
;sbeed::  db 
;sbeee::  db 
;sbeef::  db 
;sbef0::  db 
;sbef1::  db 
;sbef2::  db 
;sbef3::  db 
;sbef4::  db 
;sbef5::  db 
;sbef6::  db 
;sbef7::  db 
;sbef8::  db 
;sbef9::  db 
;sbefa::  db 
;sbefb::  db 
;sbefc::  db 
;sbefd::  db 
;sbefe::  db 
;sbeff::  db 
;sbf00::  db 
;sbf01::  db 
;sbf02::  db 
;sbf03::  db 
;sbf04::  db 
;sbf05::  db 
;sbf06::  db 
;sbf07::  db 
;sbf08::  db 
;sbf09::  db 
;sbf0a::  db 
;sbf0b::  db 
;sbf0c::  db 
;sbf0d::  db 
;sbf0e::  db 
;sbf0f::  db 
;sbf10::  db 
;sbf11::  db 
;sbf12::  db 
;sbf13::  db 
;sbf14::  db 
;sbf15::  db 
;sbf16::  db 
;sbf17::  db 
;sbf18::  db 
;sbf19::  db 
;sbf1a::  db 
;sbf1b::  db 
;sbf1c::  db 
;sbf1d::  db 
;sbf1e::  db 
;sbf1f::  db 
;sbf20::  db 
;sbf21::  db 
;sbf22::  db 
;sbf23::  db 
;sbf24::  db 
;sbf25::  db 
;sbf26::  db 
;sbf27::  db 
;sbf28::  db 
;sbf29::  db 
;sbf2a::  db 
;sbf2b::  db 
;sbf2c::  db 
;sbf2d::  db 
;sbf2e::  db 
;sbf2f::  db 
;sbf30::  db 
;sbf31::  db 
;sbf32::  db 
;sbf33::  db 
;sbf34::  db 
;sbf35::  db 
;sbf36::  db 
;sbf37::  db 
;sbf38::  db 
;sbf39::  db 
;sbf3a::  db 
;sbf3b::  db 
;sbf3c::  db 
;sbf3d::  db 
;sbf3e::  db 
;sbf3f::  db 
;sbf40::  db 
;sbf41::  db 
;sbf42::  db 
;sbf43::  db 
;sbf44::  db 
;sbf45::  db 
;sbf46::  db 
;sbf47::  db 
;sbf48::  db 
;sbf49::  db 
;sbf4a::  db 
;sbf4b::  db 
;sbf4c::  db 
;sbf4d::  db 
;sbf4e::  db 
;sbf4f::  db 
;sbf50::  db 
;sbf51::  db 
;sbf52::  db 
;sbf53::  db 
;sbf54::  db 
;sbf55::  db 
;sbf56::  db 
;sbf57::  db 
;sbf58::  db 
;sbf59::  db 
;sbf5a::  db 
;sbf5b::  db 
;sbf5c::  db 
;sbf5d::  db 
;sbf5e::  db 
;sbf5f::  db 
;sbf60::  db 
;sbf61::  db 
;sbf62::  db 
;sbf63::  db 
;sbf64::  db 
;sbf65::  db 
;sbf66::  db 
;sbf67::  db 
;sbf68::  db 
;sbf69::  db 
;sbf6a::  db 
;sbf6b::  db 
;sbf6c::  db 
;sbf6d::  db 
;sbf6e::  db 
;sbf6f::  db 
;sbf70::  db 
;sbf71::  db 
;sbf72::  db 
;sbf73::  db 
;sbf74::  db 
;sbf75::  db 
;sbf76::  db 
;sbf77::  db 
;sbf78::  db 
;sbf79::  db 
;sbf7a::  db 
;sbf7b::  db 
;sbf7c::  db 
;sbf7d::  db 
;sbf7e::  db 
;sbf7f::  db 
;sbf80::  db 
;sbf81::  db 
;sbf82::  db 
;sbf83::  db 
;sbf84::  db 
;sbf85::  db 
;sbf86::  db 
;sbf87::  db 
;sbf88::  db 
;sbf89::  db 
;sbf8a::  db 
;sbf8b::  db 
;sbf8c::  db 
;sbf8d::  db 
;sbf8e::  db 
;sbf8f::  db 
;sbf90::  db 
;sbf91::  db 
;sbf92::  db 
;sbf93::  db 
;sbf94::  db 
;sbf95::  db 
;sbf96::  db 
;sbf97::  db 
;sbf98::  db 
;sbf99::  db 
;sbf9a::  db 
;sbf9b::  db 
;sbf9c::  db 
;sbf9d::  db 
;sbf9e::  db 
;sbf9f::  db 
;sbfa0::  db 
;sbfa1::  db 
;sbfa2::  db 
;sbfa3::  db 
;sbfa4::  db 
;sbfa5::  db 
;sbfa6::  db 
;sbfa7::  db 
;sbfa8::  db 
;sbfa9::  db 
;sbfaa::  db 
;sbfab::  db 
;sbfac::  db 
;sbfad::  db 
;sbfae::  db 
;sbfaf::  db 
;sbfb0::  db 
;sbfb1::  db 
;sbfb2::  db 
;sbfb3::  db 
;sbfb4::  db 
;sbfb5::  db 
;sbfb6::  db 
;sbfb7::  db 
;sbfb8::  db 
;sbfb9::  db 
;sbfba::  db 
;sbfbb::  db 
;sbfbc::  db 
;sbfbd::  db 
;sbfbe::  db 
;sbfbf::  db 
;sbfc0::  db 
;sbfc1::  db 
;sbfc2::  db 
;sbfc3::  db 
;sbfc4::  db 
;sbfc5::  db 
;sbfc6::  db 
;sbfc7::  db 
;sbfc8::  db 
;sbfc9::  db 
;sbfca::  db 
;sbfcb::  db 
;sbfcc::  db 
;sbfcd::  db 
;sbfce::  db 
;sbfcf::  db 
;sbfd0::  db 
;sbfd1::  db 
;sbfd2::  db 
;sbfd3::  db 
;sbfd4::  db 
;sbfd5::  db 
;sbfd6::  db 
;sbfd7::  db 
;sbfd8::  db 
;sbfd9::  db 
;sbfda::  db 
;sbfdb::  db 
;sbfdc::  db 
;sbfdd::  db 
;sbfde::  db 
;sbfdf::  db 
;sbfe0::  db 
;sbfe1::  db 
;sbfe2::  db 
;sbfe3::  db 
;sbfe4::  db 
;sbfe5::  db 
;sbfe6::  db 
;sbfe7::  db 
;sbfe8::  db 
;sbfe9::  db 
;sbfea::  db 
;sbfeb::  db 
;sbfec::  db 
;sbfed::  db 
;sbfee::  db 
;sbfef::  db 
;sbff0::  db 
;sbff1::  db 
;sbff2::  db 
;sbff3::  db 
;sbff4::  db 
;sbff5::  db 
;sbff6::  db 
;sbff7::  db 
;sbff8::  db 
;sbff9::  db 
;sbffa::  db 
;sbffb::  db 
;sbffc::  db 
;sbffd::  db 
;sbffe::  db 
;sbfff::  db 
